# Generated by Django 6.0 on 2026-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_instagram',
            field=models.BooleanField(default=False),
        ),
    ]
